import {execFileSync} from 'node:child_process';
import {repoRoot,build} from './build.mjs';
import {verify} from './verify.mjs';
const git=(...args)=>execFileSync('git',args,{cwd:repoRoot,encoding:'utf8'}).trim();
const expected='https://github.com/nastajus/nastajus.github.io.git';
if(git('remote','get-url','origin')!==expected)throw Error('Unexpected remote; refusing publication');
if(git('branch','--show-current')!=='master')throw Error('Publish from master only');
const allowed=file=>file.startsWith('postings/')||file.startsWith('_tools/postings/')||file==='.gitignore';
if(git('diff','--cached','--name-only').split('\n').filter(Boolean).some(file=>!allowed(file)))throw Error('Unrelated files are staged; commit them separately');
git('pull','--ff-only','origin','master');
await build();
execFileSync(process.execPath,['--test','tests/extract.test.mjs'],{cwd:new URL('.',import.meta.url),stdio:'inherit'});
await verify();
git('add','--','postings','_tools/postings','.gitignore');
if(git('diff','--cached','--name-only'))git('commit','-m','Update shareable saved job postings');
git('push','origin','master');
console.log('Pushed. GitHub Pages will deploy /postings/ automatically. Check Pages build status before sharing new links.');
