import {esc} from './extract.mjs';
export const formatDate=value=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit',timeZoneName:'short'}).format(new Date(value));
export const day=value=>new Intl.DateTimeFormat('en-CA',{timeZone:'UTC',weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(new Date(value+'T12:00:00Z'));
const copy=url=>`<button class="copy" data-copy="${esc(url)}" aria-label="Copy share link">Copy link</button>`;
export function shell(title,body,state,current,extra=''){
 const bursts=state.bursts.map(b=>`<a ${current.startsWith(b.path)?'aria-current="page"':''} href="${b.path}">${esc(b.label)}</a>`).join('');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex, nofollow"><meta name="referrer" content="no-referrer"><title>${esc(title)} · Job Shelf</title><link rel="canonical" href="${state.siteUrl+current}"><link rel="stylesheet" href="/postings/assets/style.css"><script defer src="/postings/assets/app.js"></script></head><body><a class="skip" href="#main">Skip to content</a><button id="sidebar-toggle" aria-label="Toggle sidebar" aria-expanded="true" aria-controls="sidebar" title="Ctrl Shift S">☰</button><aside id="sidebar"><a class="brand" href="/postings/"><span class="brand-icon">▤</span> Job Shelf</a><p class="sidebar-caption">A personal shortlist</p><nav><a href="/postings/" ${current==='/postings/'?'aria-current="page"':''}>All saved postings</a><div class="nav-label">SEARCH BURSTS</div>${bursts}${extra}<div class="nav-label">ELSEWHERE</div><a href="https://jobboard.jvstoronto.org/" target="_blank" rel="noopener">JVS job board ↗</a><a href="https://nastajus.github.io/">Ian’s home page ↗</a></nav><p class="sidebar-note">Saved copies stay linkable even when a live posting changes.</p><small>Ctrl Shift S toggles this sidebar.</small></aside><main id="main">${body}<footer>Personal saved-posting archive · Dates shown in Toronto time.<br>Saved copies describe the capture date; current availability is unknown.</footer></main><div id="toast" role="status" aria-live="polite"></div><dialog id="copy-dialog"><form method="dialog"><h2>Share this link</h2><p>Copy the selected URL:</p><input id="copy-value" aria-label="Share URL" readonly><button>Close</button></form></dialog></body></html>`;
}
function card(entry,state){return `<article class="posting" data-search="${esc([entry.title,entry.jobNumber,entry.location,entry.department,entry.hours].join(' ').toLowerCase())}"><div><div class="card-kicker">${esc(entry.jobNumber)}${entry.hidden?' · NVM':''}</div><h3><a href="${entry.path}">${esc(entry.title)}</a></h3><p class="description">${esc(entry.location||'Location not specified')}${entry.hours?' · '+esc(entry.hours):''}</p><p class="saved">Saved <time datetime="${entry.savedAt}">${formatDate(entry.savedAt)}</time></p></div><div class="card-actions">${copy(state.siteUrl+entry.path)}<a class="open" href="${entry.path}">Open posting <span aria-hidden="true">↗</span></a></div></article>`;}
function groups(entries,state,burst,reveal=false){
 const grouped=new Map();for(const e of entries){const key=e.groupPath;if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(e);}
 return [...grouped].sort(([a],[b])=>a.localeCompare(b)).map(([group,list])=>{
  const sample=list[0],cards=list.sort((a,b)=>a.title.localeCompare(b.title)).map(e=>card(e,state)).join('');
  if(!group)return `<section class="group"><h2>Postings of interest <span class="count">${list.length}</span></h2><div class="cards">${cards}</div></section>`;
  const label=sample.groupLabel;
  return `<details class="group ${sample.hidden?'nvm':''}" id="group-${esc(burst.slug+'-'+group.replaceAll('/','-'))}" ${sample.hidden&&!reveal?'':'open'}><summary>${esc(label)} <span class="count">${list.length}</span><span class="summary-note">${sample.hidden?'Set aside · expand to view':'Saved folder'}</span></summary><p class="group-note">${sample.hidden?'Hidden from the default view, but these pages are public and shareable.':'Preserves the source folder grouping.'} <a href="${burst.path+group+'/'}">Open group index ↗</a></p><div class="cards">${cards}</div></details>`;
 }).join('');
}
function toolbar(){return `<div class="toolbar"><label for="search">Find a saved posting</label><input id="search" type="search" placeholder="Search title, location, department or job number…"><p id="search-status" aria-live="polite"></p></div>`;}
function attachments(items,state){return items.length?`<details class="references"><summary>Reference images <span class="count">${items.length}</span></summary>${items.map(a=>`<figure><a href="${a.path}"><img src="${a.path}" loading="lazy" alt="${esc(a.title)}"></a><figcaption>${esc(a.title)} · File saved ${formatDate(a.savedAt)} ${copy(state.siteUrl+a.path)}</figcaption></figure>`).join('')}</details>`:'';}
export function rootPage(state){
 const visible=state.entries.filter(e=>!e.hidden).length,hidden=state.entries.length-visible;
 const body=`<header><div class="eyebrow">IAN’S JOB SEARCH</div><h1>Job Shelf</h1><p class="lead">Interesting work, collected in one place.</p></header><div class="overview"><div><strong>${visible}</strong><span>postings of interest</span></div><div><strong>${hidden}</strong><span>set aside in NVM</span></div><div><strong>${state.bursts.length}</strong><span>search ${state.bursts.length===1?'burst':'bursts'}</span></div></div><section><h2>Search bursts</h2><div class="bursts">${state.bursts.map(b=>`<article class="burst"><div class="card-kicker">${esc(b.sourceLabel)}</div><h3><a href="${b.path}">${esc(b.label)}</a></h3><p>Searched ${day(b.searchedOn)}</p><a href="${b.path}">Open this search →</a> ${copy(state.siteUrl+b.path)}</article>`).join('')}</div></section>${toolbar()}${state.bursts.map(b=>`<section class="burst-list"><div class="section-heading"><h2><a href="${b.path}">${esc(b.label)}</a></h2><span>${day(b.searchedOn)}</span></div>${groups(state.entries.filter(e=>e.burst===b.key),state,b)}</section>`).join('')}`;
 return shell('Job Shelf',body,state,'/postings/');
}
export function burstPage(state,burst,groupPath=null){
 const entries=state.entries.filter(e=>e.burst===burst.key&&(groupPath===null||e.groupPath===groupPath));
 const groupLabel=groupPath!==null?entries[0]?.groupLabel||groupPath:'';
 const current=burst.path+(groupPath?groupPath+'/':'');
 const body=`<div class="breadcrumb"><a href="/postings/">All postings</a> / <a href="${burst.path}">${esc(burst.label)}</a>${groupPath?' / '+esc(groupLabel):''}</div><header><div class="eyebrow">${esc(burst.sourceLabel)}</div><h1>${esc(groupLabel||burst.label)}</h1><p class="lead">Searched ${day(burst.searchedOn)}.</p><div class="header-actions">${copy(state.siteUrl+current)}<span>${entries.length} saved postings</span></div></header>${toolbar()}${groups(entries,state,burst,groupPath!==null)}${groupPath===null?attachments(state.attachments.filter(a=>a.burst===burst.key),state):''}`;
 const nvmGroups=[...new Map(state.entries.filter(e=>e.burst===burst.key&&e.groupPath).map(e=>[e.groupPath,e])).values()];
 const extra=nvmGroups.length?`<details class="nav-groups"><summary>Saved folders</summary>${nvmGroups.map(e=>`<a href="${burst.path+e.groupPath+'/'}">${esc(e.groupLabel)}</a>`).join('')}</details>`:'';
 return shell(groupLabel||burst.label,body,state,current,extra);
}
export function detailPage(state,entry,content){
 const burst=state.bursts.find(b=>b.key===entry.burst);
 const body=`<div class="breadcrumb"><a href="/postings/">All postings</a> / <a href="${burst.path}">${esc(burst.label)}</a>${entry.groupPath?` / <a href="${burst.path+entry.groupPath+'/'}">${esc(entry.groupLabel)}</a>`:''}</div><header><div class="eyebrow">SAVED JVS POSTING${entry.hidden?' · NVM':''}</div><h1>${esc(entry.title)}</h1><p class="lead">${esc(entry.location||entry.department)}</p><div class="header-actions">${copy(state.siteUrl+entry.path)}<a class="button secondary" href="saved.html" target="_blank" rel="noopener">Open saved-page view ↗</a></div></header><dl class="metadata"><div><dt>Job number</dt><dd>${esc(entry.jobNumber)}</dd></div><div><dt>Saved</dt><dd><time datetime="${entry.savedAt}">${formatDate(entry.savedAt)}</time></dd></div><div><dt>Searched</dt><dd>${day(burst.searchedOn)}</dd></div><div><dt>Source</dt><dd>${esc(burst.sourceLabel)}</dd></div></dl>${entry.hidden?'<p class="notice">NVM / set aside. This group is collapsed on the main index, but this link is publicly accessible.</p>':''}${entry.title!==entry.sourceTitle?`<p class="notice">Title shown here follows the job description. The captured Job Title field reads “${esc(entry.sourceTitle)}”.</p>`:''}<article class="job-content">${content}</article><details class="provenance"><summary>Source & capture details</summary><p>Saved timestamp: ${esc(entry.savedAtBasis)}.</p><p>File created: ${formatDate(entry.fileCreatedAt)}<br>File modified: ${formatDate(entry.fileModifiedAt)}</p><p><a href="${esc(entry.sourceUrl)}" target="_blank" rel="noopener">Original captured JVS page ↗</a> — sign-in may be required. The captured URL is a generic job-details page and may not restore this exact posting; use the job number above.</p>${entry.applicationUrl?`<p><a href="${esc(entry.applicationUrl)}" target="_blank" rel="noopener">JVS application page for this posting ↗</a></p>`:''}<p>The saved-page copy retains the capture’s layout and embedded assets. Account navigation and active controls were removed for sharing. The local original is unchanged.</p></details>`;
 return shell(entry.title,body,state,entry.path);
}
export function yearPage(state,year){return shell(String(year),`<header><div class="eyebrow">SEARCH ARCHIVE</div><h1>${year}</h1></header><div class="bursts">${state.bursts.filter(b=>b.year===year).map(b=>`<article class="burst"><h2><a href="${b.path}">${esc(b.label)}</a></h2><p>${day(b.searchedOn)}</p></article>`).join('')}</div>`,state,`/postings/${year}/`);}
